# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c91d72afb481bd6cf573340e11088232e439ee8a3f94fa3d4d079137d14e6a168d8fc9b9d3475641ca4270085a06e1bc0b1d8a216a55fda4efb5aef0adcdf910

test:
  secret_key_base: 27ec8911b13d2f99c75c3d6735529cdbec0f29050bed09eeff6895e60e335505d8c11e03e7d6b9c2e4a093b51e9fffb5e32b589b6cb4662692c5540ab76a95a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
